/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agendarSala;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felipex
 */
public class TelaManipulacaoGerente extends javax.swing.JFrame {

    private DB bancoDados;
    private PreparedStatement pstConsulta, pstConsulta2; 
    private ResultSet rsResultado, rsResultado2;
    private JScrollPane scrollTable;
    private JTable jTable;

    /**
     * Creates new form TelaManipulacaoGerente
     */
    public TelaManipulacaoGerente() {
        initComponents();
        inicializaComponentes();
        definirEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btVisualisarSalasGerente = new javax.swing.JButton();
        btCancelarAgend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCancelarAgen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Manipulacao - Gerente");
        setBounds(new java.awt.Rectangle(500, 200, 300, 300));

        btVisualisarSalasGerente.setText("Visualizar Sala(s) Agendada(s)");

        btCancelarAgend.setText("Cancelar Agendamento(s)");
        btCancelarAgend.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btCancelarAgendComponentAdded(evt);
            }
        });
        btCancelarAgend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarAgendActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione a Opção desejada:");

        jLabel2.setText("Informe o ID do agendamento que deseja cancelar:");

        tfCancelarAgen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCancelarAgenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btCancelarAgend))
                            .addComponent(btVisualisarSalasGerente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCancelarAgen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVisualisarSalasGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelarAgend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCancelarAgen, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializaComponentes() {

        scrollTable = new JScrollPane();
        scrollTable.setBounds(30, 130, 750, 300);

        add(scrollTable);

        bancoDados = new DB();
    }

    public void definirEventos() {
        btVisualisarSalasGerente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    if (!bancoDados.getConnectiom()) {
                        JOptionPane.showMessageDialog(null, "Falha ao conectar no banco de dados! "
                                + "O sistema será encerrado!");
                        System.exit(0);
                    }

                    pstConsulta = bancoDados.connection.prepareStatement("Select * from scheduling ");
                    rsResultado = pstConsulta.executeQuery();
                    DefaultTableModel tableModel = new DefaultTableModel(new String[]{}, 0) {
                    };

                    int qtdeColunas = rsResultado.getMetaData().getColumnCount();
                    for (int indice = 1; indice <= qtdeColunas; indice++) {
                        tableModel.addColumn(rsResultado.getMetaData().getColumnName(indice));
                    }

                    jTable = new JTable(tableModel);
                    DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();

                    while (rsResultado.next()) {
                        try {
                            String[] dados = new String[qtdeColunas];
                            for (int i = 1; i <= qtdeColunas; i++) {
                                dados[i - 1] = rsResultado.getString(i);
                                System.out.println(rsResultado.getString(i));
                            }
                            dtm.addRow(dados);
                            System.out.println();
                        } catch (SQLException erroSql) {
                        }
                        scrollTable.setViewportView(jTable);
                    }

                    rsResultado.close();
                    pstConsulta.close();
                    bancoDados.close();

                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Comando SQL Inválido " + erro.toString());
                }
            }
        });

        btCancelarAgend.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (tfCancelarAgen.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Informe um número válido.");
                    return;
                }
                try {
                    if (!bancoDados.getConnectiom()) {
                        JOptionPane.showMessageDialog(null, "Falha ao conectar no banco de dados! "
                                + "O sistema será encerrado!");
                        System.exit(0);
                    }

                    pstConsulta2 = bancoDados.connection.prepareStatement("Delete from scheduling where id = " + tfCancelarAgen.getText());
                    rsResultado2 = pstConsulta2.executeQuery();
                    DefaultTableModel tableModel = new DefaultTableModel(new String[]{}, 0) {
                    };

                    int qtdeColunas = rsResultado.getMetaData().getColumnCount();
                    for (int indice = 1; indice <= qtdeColunas; indice++) {
                        tableModel.addColumn(rsResultado2.getMetaData().getColumnName(indice));
                    }

                    jTable = new JTable(tableModel);
                    DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();

                    while (rsResultado2.next()) {
                        try {
                            String[] dados = new String[qtdeColunas];
                            for (int i = 1; i <= qtdeColunas; i++) {
                                dados[i - 1] = rsResultado2.getString(i);
                                System.out.println(rsResultado2.getString(i));
                            }
                            dtm.addRow(dados);
                            System.out.println();
                        } catch (SQLException erroSql) {
                        }
                        scrollTable.setViewportView(jTable);
                    }

                    rsResultado2.close();
                    pstConsulta2.close();
                    bancoDados.close();

                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, "Comando SQL Inválido " + erro.toString());
                }
            }
        });
    }


    private void btCancelarAgendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarAgendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarAgendActionPerformed

    private void btCancelarAgendComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btCancelarAgendComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelarAgendComponentAdded

    private void tfCancelarAgenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCancelarAgenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCancelarAgenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaManipulacaoGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaManipulacaoGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaManipulacaoGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaManipulacaoGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaManipulacaoGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelarAgend;
    private javax.swing.JButton btVisualisarSalasGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfCancelarAgen;
    // End of variables declaration//GEN-END:variables
}
